<div id="wrap">
<div style="clear:both;"></div>

<div id="footer">
    	<div class="building"></div>
        <div class="detail">
        	<div class="container">
            	<div class="blog">
                    <div class="text">
                    {% for i, article in guest.kb_article_get_list({"per_page":1}).list %}
                    	<span><a href="{{ '/kb'|link }}/{{article.category.slug}}/{{kbarticle.slug}}" style="color:#FFF;">{{article.title|truncate(30)}}</a> <span class="date">{{article.created_at|bb_date}}</span></span>
                        <div class="clear"></div>
                        {% endfor %}
                    </div>
                </div>
                
                <div class="email">
                	<input name="" type="text" value="Email Address">
                    <input name="" type="submit" value="submit">
                </div>
                <div class="clear"></div>
            </div>
        </div>
        
        <div class="footer_bot">
        	<div class="container">
            <div class="links">
            	{% if guest.extension_is_on({"mod":'kb'}) %}
                	<h3>{% trans 'Popular articles' %}</h3>
                    <ul>
                        {% for i, article in guest.kb_article_get_list({"per_page":4}).list %}
                            <li><a href="{{ '/kb'|link }}/{{article.category.slug}}/{{article.slug}}">{{article.title|truncate(30)}}</a></li>
                        {% endfor %}
                    </ul>
        		{% endif %}
            </div>
            
            <div class="links">
            	{% if guest.extension_is_on({"mod":'news'}) %}
                <h3>{% trans 'Recent posts' %}</h3>
                    <ul>
                        {% set posts = guest.news_get_list({"per_page": 4}) %}
                        {% for i, post in posts.list %}
                        <li>
                            <a href="{{ '/blog'|link }}/{{post.slug}}">{{post.title|truncate(30)}}</a>
                        </li>
                        {% endfor %}
                    </ul>
        		{% endif %}
            </div>
            
            <div class="links">
            	<h3>{{ company.name }}</h3>
                    <ul>
                        <li>
                            <a href="{{ '/about-us'|link }}">{% trans 'About us' %}</a>
                        </li>
                        <li>
                            <a href="{{ '/tos'|link }}">{% trans 'Terms and conditions' %}</a>
                        </li>
                        <li>
                            <a href="{{ '/privacy-policy'|link }}">{% trans 'Privacy policy' %}</a>
                        </li>
                        {% if guest.extension_is_on({"mod":'branding'}) %}
                        <li>
                            <a href="http://www.boxbilling.com" title="Billing Software" target="_blank">Billing software</a>
                        </li>
                        {% endif %}
                    </ul>
            </div>
            
            <div class="links">
            	<h3>{% trans 'Social Connection' %}</h3>
                <div class="social">
                    <ul>
                        <li class="fb"><a href="#.">Facebook</a></li>
                        <li class="tw"><a href="#.">View Cart</a></li>
                        <li class="gp"><a href="#.">My Wishlist</a></li>
                    </ul>
                </div>
            </div>
            
            <div class="links last">
            	<h3>{% trans 'Info' %}</h3>
                <div class="get_touch">
                	<ul>
                    	<li class="mb"><a>{{ company.tel }}</a></li>
                        <li class="email"><a>{{ company.email }}</a></li>
                        <li class="address"><a>{{ company.address_1 }}, {{ company.address_2 }} {{ company.address_3 }}</a></li>
                    </ul>
                </div>
            </div>
            
            
            </div>
        <div class="clear"></div>    
        </div>
        
        <div class="copyright">
        	<div class="container">
            	<p>Copyright © {{ now|date('Y') }} {{ company.signature }}</p>
            </div>
        </div>
            
    </div>

</div>
{% block js %}{% endblock %}

<script type="text/javascript">
        $(document).ready(function() {

            $(".signin").click(function(e) {          
				e.preventDefault();
                $("fieldset#signin_menu").toggle();
				$(".signin").toggleClass("menu-open");
            });
			
			$("fieldset#signin_menu").mouseup(function() {
				return false
			});
			$(document).mouseup(function(e) {
				if($(e.target).parent("a.signin").length==0) {
					$(".signin").removeClass("menu-open");
					$("fieldset#signin_menu").hide();
				}
			});			
			
        });
</script>

<script type='text/javascript'>
    $(function() {
	  $('#forgot_username_link').tipsy({gravity: 'w'});   
    });
  </script>


</body>
</html>
