{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Payments history' %}{% endblock %}
{% set profile = client.client_get %}

{% block page_title_up %}
{% trans 'Payments history' %}
{% endblock %}

{% block content %}
<div class="domains"> 
<div class="gray">
                    	<span class="title">{% trans 'Amount' %}</span>
                        <span class="title">{% trans 'Description' %}</span>
                        <span class="title">{% trans 'Date' %}</span>
                        <div class="clear"></div>
                    </div>
                    
                    {% set transactions = client.client_balance_get_list({"per_page":10, "page":request.page}) %}
               		{% for i, tx in transactions.list %}
                    <div class="{{ cycle(['light', 'dark'], i) }}">
                    	<span class="detail">{{ tx.amount | money(tx.currency) }}</span>
                        <span class="detail">{{tx.description}}</span>
                        <span class="detail">{{tx.created_at|bb_date}}</span>
                        <div class="clear"></div>
                    </div>
                    {% else %}
                    <div class="light">
                    <span style="width:100%;">{% trans 'The list is empty' %}</span>
                    </div>
                    {% endfor %}
                    </div>
                    {% trans 'Balance' %}: {{ profile.balance | money(profile.currency) }}
                    <br>
       
 <a href="#" class="small_btn-org table_btn" onclick="$('#widget-add-funds').slideToggle(); return false;"><span class="small_blk-org">{% trans 'Add Funds' %}</span></a> 

{% include "partial_pagination.phtml" with {'list': transactions} %}

<div style="clear:both"></div>

<div class="widget" style="display: none;" id="widget-add-funds">
<br>
<div class="container">

        <h2>{% trans 'Add funds in advance'%}</h2>

    <div class="form" style="float:left;">
    
        <p>{% trans 'You can add funds to your account if you have active order.' %}</p>
        <form action="" method="post" class="api_form" data-api-url="client/invoice/funds_invoice" data-api-jsonp="onAfterInvoiceCreated">
          <div id="error" class="warning" style="display:none;"></div>
           		<div class="field">
             	<label>{% trans 'Amount' %}:</label>
                <input name="amount" id="amount" type="text" value="" required="required">
                </div>
               
             
                <input class="bb-button bb-button-submit" type="submit" value="">
            
        </form>
    </div>
</div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
    function onAfterInvoiceCreated(hash) {
        var link = '{{ "invoice"|link }}/' + hash;
        bb.redirect(link);
    }
</script>
{% endblock %}
