{% extends request.ajax ? "layout_blank.phtml" : "layout_default_tab.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{{ticket.subject}}{% endblock %}

{% block page_title_up %}
<div class="page_title">

	<div class="container">
		<div class="leaft_title"><h1>{{ ticket.subject|truncate(60) }}</h1></div>
        <div class="reght_pagenation">#{{ ticket.id }} - {{ticket.helpdesk.name}}</div>
	</div>
    
</div>
{% endblock %}

{% block content %}

<div class="text">
        <h2>{% trans 'Ticket details' %}</h2>

     <table>
            <tbody>
                <tr>
                    <td>{% trans 'Ticket ID' %}</td>
                    <td><b>#{{ticket.id}}</b></td>
                </tr>

                <tr>
                    <td>{% trans 'Help desk' %}</td>
                    <td>{{ticket.helpdesk.name}}</td>
                </tr>

                <tr>
                    <td>{% trans 'Status' %}</td>
                    <td>{{mf.status_name(ticket.status)}}</td>
                </tr>

                <tr>
                    <td>{% trans 'Time opened' %}</td>
                    <td>{{ticket.created_at|bb_date }}</td>
                </tr>

                {% if ticket.rel_type == 'order' and ticket.rel_id %}
                <tr>
                    <td>{% trans 'Related to' %}</td>
                    <td><a href="{{ 'service/manage'|link }}/{{ ticket.rel_id }}">{% trans 'Service #' %} {{ ticket.rel_id }}</a></td>
                </tr>
                {% endif %}
             </tbody>

             <tfoot>
                 <tr>
                     <td colspan="2">

                     <a class="small_btn-grn buy_now" href="{{ '/support'|link }}"><span class="small_blk-grn">{% trans 'Tickets list' %}</span></a>

                     {% if ticket.status != 'closed' %}
                     <a href="#" class="small_btn-blk buy_now" id="ticket-close" style="margin-left:10px;"><span class="small_blk-blk">{% trans 'Close ticket' %}</span></a>
                        {% endif %}
                     </td>
                 </tr>
             </tfoot>
        </table>
    <Br />
</div>

    {% for i, message in ticket.messages %}
    
    <div id="features-toggle">
   
      <div class="left">
        <ul>
        <li class="features"><a name="m-{{message.id}}" class="selected" id="selected"><div class="icon1"></div><div class="text">{{ i+1 }}</div></a></li>
        <li class="features"><a name="reply-{{message.id}}" class="" id=""><div class="icon2"></div><div class="text">{% trans 'Reply' %}</div></a></li>
        <li class="features"><a name="quote-{{message.id}}" class="" id=""><div class="icon3"></div><div class="text">{% trans 'Quote' %}</div></a></li>
        </ul>        
      </div>
          
      <div class="right">
		 <div id="m-{{message.id}}">
        
          <div class="detail">

            <p style="float:left;">
                <h1>Creative</h1>
                {% trans 'Author' %} : {{ message.author.name }}<br>
                {{ message.created_at|bb_date }}
                {{ message.content|bbmd }}
			</p>
          </div>
          </div>
          
          
          <div id="reply-{{message.id}}" style="display: none;">
        
          <div class="detail form">

            <p style="float:left;">
                <h1>{% trans 'Reply' %}</h1>
                <form method="post" action="" class="api_form" data-api-url="guest/support/ticket_reply" data-api-reload="1">
					
                    <div class="field">
                    	<label></label>
                        <textarea name="message" id="message" cols="" rows="" required style="height: 112px !important;"></textarea>
                    </div>

                        <input type="hidden" name="hash" value="{{ ticket.hash }}" />
                        <input class="comment_submit" type="submit" value="">

                </form>	
			</p>
            
          </div>
          <div style="clear:both"></div>
          </div>
          
           <div id="quote-{{message.id}}" style="display: none;">
        
          <div class="detail form">

            <p style="float:left;">
                <h1>{% trans 'Quote' %}</h1>
                <form method="post" action="" class="api_form" data-api-url="guest/support/ticket_reply" data-api-reload="1">
					<div class="field">
                    	<label></label>
                        <textarea name="message" id="message" cols="" rows="" required style="height: 112px !important;">{{ mf.markdown_quote(message.content) }}</textarea>
                    </div>
                       
                        <input type="hidden" name="hash" value="{{ ticket.hash }}" />
                        <input class="comment_submit" type="submit" value="">

                </form>	
			</p>
          </div>
        
        </div>
        
        
        
      </div>
      
    </div>
 			
		<div style="clear:both;"></div>
    {% endfor %}
</div>
            
            </div>
            <div style="clear:both;"></div>
{% endblock %}

{% block js %}
<script type="text/javascript">
	$(document).ready(function(){
		$("#textExample").verticaltabs({speed: 500,slideShow: false,activeIndex: 2});
		$("#imageExample").verticaltabs({speed: 1000,slideShow: true,slideShowSpeed: 3000,activeIndex: 0,playPausePos: "topRight"});
	});
</script>

<script>
$(document).ready(function(){
  $('li.features a').click(function () {
      var divname= this.name;
      $("#"+divname).show(0).siblings().hide(0);
      $('li.features a').removeClass('selected'); $(this).addClass('selected');
  });
});
</script>

<script type="text/javascript">
$(function() {

    $('#ticket-close').bind('click',function(event){
        bb.post(
            'client/support/ticket_close',
            { id: {{ ticket.id }} },
            function(result) {
                bb.redirect('{{ "support"|link }}');
            }
        );
        return false;
    });
});
</script>
{% endblock %}