{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{{product.title}}{% endblock %}

{% block page_title_up %}
{{ product.title }}
<p>{% trans 'Please configure domain for your hosting account' %}</p>
{% endblock %}

{% block content %}

{% include "partial_steps.phtml" with {'selected': 2} %}

{% set periods = guest.system_periods %}
{% set pricing = product.pricing %}
<style>
.in {
background: #f7f7f7;
width: 284px;
height: 36px;
padding: 0 5px;
border: none;
color: #898989;
border: solid 1px #d8d8d8;
border-radius: 5px;
-moz-border-radius: 5px;
-webkit-border-radius: 5px;	
}
</style>

<div class="form" style="width: 100%;">
<form method="post" action="" class="api_form" data-api-url="guest/cart/add_item" data-api-redirect="{{ 'cart'|link }}">

                    <ul class="tabs">
                        <li><a href="#owndomain" rel="owndomain"><span class="dark-icon"></span>{% trans 'Use own' %}</a></li>
                        <li><a href="#register" rel="register"><span class="dark-icon"></span>{% trans 'Register' %}</a></li>
                        <li><a href="#transfer" rel="transfer"><span class="dark-icon"></span>{% trans 'Transfer' %}</a></li>
                    </ul>

                    <div class="tabs_container">

                        <div class="tab_content" id="owndomain" style="width:100%;">
                        <Br />
                            <h2>{% trans 'I will use my existing domain and update nameservers' %}</h2>
                                <p>
                                    <input type="text" name="domain[owndomain_sld]" value="{{ request.owndomain_sld }}" style="width: 321px" class="in" placeholder="{% trans 'Enter your domain name' %}">
                                    <input type="text" name="domain[owndomain_tld]" value="{{ request.owndomain_tld|default('.com') }}" class="in" style="width: 80px">
                                </p>
                        </div>

                        <div class="tab_content" id="register">
								<Br />
                                <h2>{% trans 'Register a new domain' %}</h2>
                                <p>
                                    <input type="text" name="domain[register_sld]" value="{{ request.register_sld }}" class="in" style="width: 333px" placeholder="{% trans 'Enter your domain name' %}">
                                    {{ mf.selectboxtld('domain[register_tld]', guest.serviceDomain_tlds({"allow_register":1})) }} <a href="#" class="btn-grn domain_button" id="domain-check" style="float:right; margin-right:15%;"><span class="blk-grn">{% trans 'Check' %}</span></a>
                                </p>
                                
								<Br />
                                <div id="domain-config" style="display:none;">
                                    <label>{% trans 'Period' %}:
                                    {{ mf.selectbox('domain[register_years]', {}) }}</label>
                                </div>

                        </div>

                        <div class="tab_content" id="transfer">
                            <br>
                                <h2>{% trans 'Transfer your domain from another registrar' %}</h2>
                                <p>
                                    <input type="text" name="domain[transfer_sld]" value="{{ request.transfer_sld }}" class="in" style="width: 333px" placeholder="{% trans 'Enter your domain name' %}">
                                    {{ mf.selectboxtld('domain[transfer_tld]', guest.serviceDomain_tlds({"allow_transfer":1})) }} <a href="#" class="btn-grn domain_button" id="transfer-check" style="float:right; margin-right:15%;"><span class="blk-grn">{% trans 'Check' %}</span></a>
                                </p>
                               
                            
                                <div id="domain-transfer-config" style="display:none;">
                                    <p>{% trans 'Transfer price'%}: <span id="transfer-price"></span></p>
                                    <input type="text" name="domain[transfer_code]" value="{{ request.transfer_code }}" class="in" style="width: 200px" placeholder="{% trans 'Enter domain transfer code' %}">
                                </div>

                        </div>

                    </div>
                
                <Br />
                {% include 'partial_pricing.phtml' with {'product': product} %}
            
            
            <div class="clear"></div>

    {% include 'partial_addons.phtml' with {'product': product} %}
    
    <input type="hidden" name="domain[action]" value="owndomain" id="domain-action"/>
    <input type="hidden" name="id" value="{{ product.id }}" />
</form>
</div>
{% include 'partial_currency.phtml' %}
{% endblock %}

{% block js %}

{% set currency = guest.cart_get_currency %}
<script type="text/javascript">
$(function() {

    $('ul.tabs li a').bind('click', function (){
        $('#domain-action').val($(this).attr('rel'));

        $(this).parents('ul').find('span.dark-icon')
            .removeClass('i-check i-uncheck')
            .addClass('i-uncheck');

        $(this).find('span')
            .removeClass('i-uncheck')
            .addClass('i-check');
    });
    $('ul.tabs li a:first').click();

    $('#transfer-check').bind('click',function(event){
        var sld = $('input[name="domain[transfer_sld]"]').val();
        var tld = $('select[name="domain[transfer_tld]"]').val();
        var domain = sld + tld;
        bb.post(
            'guest/servicedomain/can_be_transferred',
            { sld: sld, tld: tld },
            function(result) {
                setTransferPricing(tld);
                $('#domain-transfer-config').fadeIn('slow');
            }
        );
        return false;
    });

    $('#domain-check').bind('click',function(event){
        var sld = $('input[name="domain[register_sld]"]').val();
        var tld = $('select[name="domain[register_tld]"]').val();
        var domain = sld + tld;
        bb.post(
            'guest/servicedomain/check',
            { sld: sld, tld: tld },
            function(result) {
                setRegistrationPricing(tld);
                $('#domain-config').fadeIn('slow');
            }
        );
        return false;
    });

    if($(".addons").length && $(".addons").is(':hidden')) {
        $('#order-button').one('click', function(){
            $(this).slideUp('fast');
            $('.addons').slideDown('fast');
            return false;
        });
    }

    $('#period-selector').change(function(){
        $('.period').hide();
        $('.period.' + $(this).val()).show();
    }).trigger('change');

    $('.addon-period-selector').change(function(){
        var r = $(this).attr('rel');
        $('#' + r + ' span').hide();
        $('#' + r + ' span.' + $(this).val()).fadeIn();
    }).trigger('change');

    function setRegistrationPricing(tld)
    {
        bb.post(
            'guest/servicedomain/pricing',
            { tld: tld },
            function(result) {
                var s = $("select[name='domain[register_years]']");
                s.find('option').remove();
                for (i=1;i<6;i++) {
                    var price = bb.currency(result.price_registration, {{ currency.conversion_rate }}, "{{ currency.code }}", i);
                    s.append(new Option(i + "{% trans ' Year/s @ ' %}" + price, i));
                }
            }
        );
    }

    function setTransferPricing(tld)
    {
        bb.post(
            'guest/servicedomain/pricing',
            { tld: tld },
            function(result) {
                var price = bb.currency(result.price_transfer, {{ currency.conversion_rate }}, "{{ currency.code }}");
                $('#transfer-price').text(price);
            }
        );
    }
});
</script>
{% endblock %}