{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{% trans 'My Products & Services' %}{% endblock %}

{% block page_title_up %}
{% trans 'My Products & Services' %}
{% endblock %}

{% block content %}
<div class="domains"> 
 <div class="gray">
                    	<span class="title">{% trans 'Product/Service' %}</span>
                        <span class="title" style="width: 120px !important;">{% trans 'Price' %}</span>
                        <span class="title">{% trans 'Next due date' %}</span>
                        <span class="title" style="width: 60px !important;">{% trans 'Status' %}</span>
                        <span class="title last" style="width: 30px !important;">&nbsp;</span>
                        <div class="clear"></div>
                    </div>

                {% set orders = client.order_get_list({"per_page":10, "page":request.page, "hide_addons":1}) %}
                {% for i, order in orders.list %}
                
                <div class="{{ cycle(['light', 'dark'], i) }}">
                    	<span class="detail"><a href="{{ '/service/manage'|link }}/{{order.id}}">{{order.title}}</a></span>
                        <span class="detail" style="width: 120px !important;">{{  order.total | money(order.currency) }} {% if order.period%}{{ order.period | period_title }}{% endif %}</span>
                        <span class="detail">{% if order.expires_at %}{{order.expires_at|bb_date}}{% else %}-{% endif %}</span>
                        <span class="detail" style="width: 60px !important;">{{ mf.status_name(order.status) }}</span>
                        <span class="detail" style="width: 30px !important;"><a class="bb-button" href="{{ '/service/manage'|link }}/{{order.id}}">{% trans 'Show' %}</a></span>
                        <div class="clear"></div>
                    </div>
                {% else %}

                <div class="{{ cycle(['light', 'dark'], i) }}">
                    <span class="detail" style="width: 100% !important;">{% trans 'The list is empty' %}</span>
                </div>

                {% endfor %}
</div>

<a href="{{ 'order'|link }}" class="small_btn-grn buy_now"><span class="small_blk-grn">{% trans 'Order new service' %}</span></a>

{% include "partial_pagination.phtml" with {'list': orders} %}

{% endblock %}