{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{% trans 'Reset password' %}{% endblock %}

{% block page_title_up %}
{% trans 'How to reset my password?' %}
<p>{% trans 'Enter your email to reset password. You will receive new password after reset link is confirmed.' %}</p>
{% endblock %}

{% block content %}
<style>
.in {
background: #f7f7f7;
width: 284px;
height: 36px;
padding: 0 5px;
border: none;
color: #898989;
border: solid 1px #d8d8d8;
border-radius: 5px;
-moz-border-radius: 5px;
-webkit-border-radius: 5px;	
}
</style>
        <div class="block form" style="width: 100%;">
            <form action="" method="post" id="password-reset">
                    <label>{% trans 'Email Address' %}: </label>
                    <input type="email" name="email" class="in" value="{{ request.email }}" required>
                    <br><br>
                    <input class="bb-button bb-button-submit" type="submit" value="">
            </form>
        </div>
        
{% endblock %}

{% block js %}
<script type="text/javascript">
$(function() {
    $('#password-reset').bind('submit',function(event){
        bb.post(
            'guest/client/reset_password',
            $(this).serialize(),
            function(result) {
                bb.msg('{% trans "Password reset confirmation email was sent" %}');
            }
        );
        return false;
    });
});
</script>
{% endblock %}