{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{% trans 'Register new domain' %}{% endblock %}

{% block page_title_up %}
{% trans 'Configure' %}
 <p>{% trans 'The product/service you have chosen has the following configuration options for you to choose from.' %}</p>
{% endblock %}

{% block content %}

{% include "partial_steps.phtml" with {'selected': 2} %}

{% set periods = guest.system_periods %}
{% set pricing = product.pricing %}

<style>
.in {
background: #f7f7f7;
width: 284px;
height: 36px;
padding: 0 5px;
border: none;
color: #898989;
border: solid 1px #d8d8d8;
border-radius: 5px;
-moz-border-radius: 5px;
-webkit-border-radius: 5px;	
}
</style>

<div class="form" style="width: 100%;">
<form method="post" action="" class="api_form" data-api-url="guest/cart/add_item" data-api-redirect="{{ 'cart'|link }}">

                <ul class="tabs">
                    <li><a href="#register" rel="register"><span class="dark-icon"></span>{% trans 'Register new domain' %}</a></li>
                    <li><a href="#transfer" rel="transfer"><span class="dark-icon"></span>{% trans 'Transfer my domain' %}</a></li>
                </ul>
<Br>
                <div class="tabs_container" style="margin-top: 20px">

                    <div class="tab_content" id="register">

                  
                            <legend>{% trans 'Check domain availability' %}</legend>
                            <p>
                                <input type="text" name="register_sld" value="{{ request.register_sld }}" style="width: 400px" class="in" placeholder="{% trans 'Enter new domain name to register' %}">
                                {{ mf.selectboxtld('register_tld', guest.serviceDomain_tlds({"allow_register":1})) }}
                                
                                <a href="#" class="btn-grn domain_button" id="domain-check" style="float:right; margin-right:5%;"><span class="blk-grn">{% trans 'Check' %}</span></a>
                            </p>
                            
                            <button class="bb-button bb-button-submit bb-button-big order-button btn-grn domain_button" type="submit" style="float: right; display: none;"><span class="blk-grn">{% if product.addons|length > 0 %}{% trans 'Continue' %}{% else %}{% trans 'Order now' %}{% endif %}</span></button>
<br/><br/>
                            <div class="onAfterDomainCheck" style="display:none;">
                                <label>
                                    <select name="register_years" id="registration-years"></select>
                                </label>
                                <br/>
                                <br/>
                                <label><input type="checkbox" onclick="$('#nameservers').slideToggle();">{% trans 'I want to use my nameservers' %}</label>
                                <div id="nameservers" style="display:none; margin: 10px 0;">
                                    <p><input type="text" name="ns1" value="" class="in" placeholder="{% trans 'Nameserver 1' %}"></p><Br>
                                    <p><input type="text" name="ns2" value="" class="in" placeholder="{% trans 'Nameserver 2' %}"></p><Br>
                                    <p><input type="text" name="ns3" value="" class="in" placeholder="{% trans 'Nameserver 3' %}"></p><br/>
                                    <p><input type="text" name="ns4" value="" class="in" placeholder="{% trans 'Nameserver 4' %}"></p>
                                </div>

                            </div>
                    </div>

                    <div class="tab_content" id="transfer">
                            <p>
                                <input type="text" name="transfer_sld" class="in" value="{{ request.transfer_sld }}"  style="width: 400px" placeholder="{% trans 'Enter your domain name to transfer' %}">
                                {{ mf.selectboxtld('transfer_tld', guest.serviceDomain_tlds({"allow_transfer":1})) }}
                                <a href="#" class="btn-grn domain_button" id="transfer-check" style="float:right; margin-right:5%;"><span class="blk-grn">{% trans 'Check' %}</span></a>
                            </p>

                            <button class="bb-button bb-button-submit bb-button-big order-button btn-grn domain_button" type="submit" style="float: right; display: none;"><span class="blk-grn">{% if product.addons|length > 0 %}{% trans 'Continue' %}{% else %}{% trans 'Order now' %}{% endif %}</span></button>
<br>
                            <div id="domain-transfer-config" style="display:none;">
                                <p>{% trans 'Transfer price'%}: <span id="transfer-price"></span></p>
                                <input type="text" name="transfer_code" class="in" value="{{ request.transfer_code }}" style="width: 200px" placeholder="{% trans 'Enter domain transfer code' %}">
                            </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>

        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
    {% include 'partial_addons.phtml' with {'product': product} %}
    
<input type="hidden" name="id" value="{{ product.id }}" />
<input type="hidden" name="action" value="register" id="domain-action"/>
</form>
</div>
{% endblock %}

{% block sidebar2 %}
    {% include 'partial_currency.phtml' %}
{% endblock %}

{% block js %}
{% set currency = guest.cart_get_currency %}
<script type="text/javascript">
$(function() {

    $('ul.tabs li a').bind('click', function (){
        $('#domain-action').val($(this).attr('rel'));

        $(this).parents('ul').find('span.dark-icon')
            .removeClass('i-check i-uncheck')
            .addClass('i-uncheck');

        $(this).find('span')
            .removeClass('i-uncheck')
            .addClass('i-check');
    });
    $('ul.tabs li a:first').click();

    if($(".addons").length) {
        $('.order-button').one('click', function(){
            $(this).hide();
            $('.addons').slideDown('fast');
            return false;
        });
    }

    $('.addon-period-selector').change(function(){
        var r = $(this).attr('rel');
        $('#' + r + ' span').hide();
        $('#' + r + ' span.' + $(this).val()).fadeIn();
    }).trigger('change');

    $('#transfer-check').bind('click',function(event){
        var sld = $('input[name="transfer_sld"]').val();
        var tld = $('select[name="transfer_tld"]').val();
        var domain = sld + tld;
        bb.post(
            'guest/servicedomain/can_be_transferred',
            { sld: sld, tld: tld },
            function(result) {
                setTransferPricing(tld);
                $('#domain-name').text(domain);
                $('#domain-transfer-config').fadeIn('fast');
                $('.onAfterDomainCheck').fadeIn('fast');
                $('#transfer-check').hide();
                $('#transfer .order-button').show();
            }
        );
        return false;
    });

    $('#domain-check').bind('click',function(event){
        var sld = $('input[name="register_sld"]').val();
        var tld = $('select[name="register_tld"]').val();
        var domain = sld + tld;
        bb.post(
            'guest/servicedomain/check',
            { sld: sld, tld: tld },
            function(result) {
                setPricing(tld);
                $('#domain-name').text(domain);
                $('.onAfterDomainCheck').fadeIn('fast');
                $('#domain-check').hide();
                $('#register .order-button').show();
            }
        );
        return false;
    });

    function setPricing(tld)
    {
        bb.post(
            'guest/servicedomain/pricing',
            { tld: tld },
            function(result) {
                var s = $("#registration-years");
                s.find('option').remove();
                for (i=1;i<6;i++) {
                    var price = bb.currency(result.price_registration, {{ currency.conversion_rate }}, "{{ currency.code }}", i);
                    s.append(new Option(i + "{% trans ' Year/s @ ' %}" + price, i));
                }
            }
        );
    }

    function setTransferPricing(tld)
    {
        bb.post(
            'guest/servicedomain/pricing',
            { tld: tld },
            function(result) {
                var price = bb.currency(result.price_transfer, {{ currency.conversion_rate }}, "{{ currency.code }}");
                $('#transfer-price').text(price);
            }
        );
    }
});
</script>
{% endblock %}