{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{%trans 'Order confirm' %}{% endblock %}

{% block page_title_up %}
{% trans 'Order confirmation' %}
<p>{% trans 'These are the products you have selected' %}</p>
{% endblock %}

{% set cart = guest.cart_get %}

{% block content %}

<style>
.in {
background: #f7f7f7;
width: 284px;
height: 36px;
padding: 0 5px;
border: none;
color: #898989;
border: solid 1px #d8d8d8;
border-radius: 5px;
-moz-border-radius: 5px;
-webkit-border-radius: 5px;	
}
</style>

{% include "partial_steps.phtml" with {'selected': 3} %}

<div class="content_left">

{% if cart.items|length > 0 %}


        <div class="domains">
        			<div class="gray">
                    	<span class="title">{% trans 'Product' %}</span>
                        <span class="title">{% trans 'Period' %}</span>
                        <span class="title">{% trans 'Price' %}</span>
                        <div class="clear"></div>
                    </div>

                    {% for i, item in cart.items %}
                    <div class="{{ cycle(['light', 'dark'],i) }}">
                    	<span class="detail">{{ item.title }}
                            {% if item.quantity > 1 %}
                            x {{ item.quantity }}
                            {% endif %}</span>
                        <span class="detail">{{ item.period | period_title }}</span>
                        <span class="detail">{% if item.discount_price %}
                                <del>{{ item.price | money_convert }}</del>
                                {{ (item.price - item.discount_price) | money_convert }}
                            {% else %}
                                {{ item.price | money_convert }}
                            {% endif %}</span> 
                        <div class="clear"></div>
                    </div>
                    {% if item.setup_price != 0 %}
                    <div class="{{ cycle(['light', 'dark'],i) }}">
                    	<span class="detail">{{ item.title }} {% trans 'setup' %}</span>
                        <span class="detail">-</span>
                        <span class="detail">{% if item.discount_setup %}
                                <del>{{ item.setup_price | money_convert }}</del>
                                {{ (item.setup_price - item.discount_setup) | money_convert }}
                            {% else %}
                                {{ item.setup_price | money_convert }}</td>
                            {% endif %}</span> 
                        <div class="clear"></div>
                    </div>
                    {% endif %}
                    {% endfor %}
</div>

            {% if client %}
            <div class="grid_5 suffix_2 alpha">
                <div class="box">
                    <div class="block form" style="width:100%">
                        <form action="guest/cart/apply_promo" method="post" class="api-form" data-api-reload="1">
                                <input type="text" name="promocode" value="{{ request.promocode|default(cart.promocode) }}" class="in" style="float:left; margin-right:10px;" required placeholder="{% trans 'Have a promo code?' %}">
                                {% if cart.promocode %}
                                <a href="guest/cart/remove_promo" class="bb-button api-link" data-api-reload="1">{% trans 'Reset' %}</a>
                                {% else %}
                                <input class="bb-button bb-button-submit comment_submit" type="submit" style="float:left; margin:0;" value="">
                                {% endif %}
                        </form>
                    </div>
                    <div style="clear:both;"></div>
                </div>
            </div>
            <div class="grid_5 omega">
                <div class="box">
                    <div class="block pricing">
                    <Br />
                        <p>{% trans 'Total:' %} <b>{{ cart.total | money_convert }}</b></p>
                        <form method="post" action="client/cart/checkout" class="api-form" data-api-jsonp="onAfterCartCheckout">
                        {% if cart.total %}
                        <Br />
                        <div style="text-align: left;">
                        <h2>{% trans 'Select Payment' %}</h2>
                        {% for gtw in guest.invoice_gateways %}
                            {% if cart.currency.code in gtw.accepted_currencies %}
                            <label><input type="radio" name="gateway_id" value="{{gtw.id}}" {{loop.first ? 'checked' : ''}}/>
                                {% trans 'Pay by' %} {{gtw.title}}
                            </label>
                            <div class="clear"></div>
                            {% endif %}
                        {% endfor %}
                        </div>
                        {% endif %}
                        <br/>
                        <button class="small_btn-org table_btn" type="submit" style="border:none;"><span class="blk-grn">{% trans 'Checkout' %}</span></button>
                        </form>
                    </div>
                </div>
            </div>
            {% else %}

            <div class="block">
                <div class="splitter">
                <div class="grid_6 alpha">
                    <div class="box">
                        <div class="block text form" style="float:left;">
                            <h2>{% trans 'Sign in' %}</h2>
                            <form action="guest/client/login" method="post" class="api-form" data-api-reload="1">
                                    <p>
                                        <label>{% trans 'Email Address' %}: </label>
                                        <input type="email" name="email" class="in" value="{{ request.email }}" required>
                                    </p>
                                    <p>
                                        <label>{% trans 'Password' %}: </label>
                                        <input type="password" name="password" class="in" value="" required>
                                    </p>
                                    <Br />
                                    <input class="" type="submit" value="" style="float:left; margin:0; margin-right: 10px; margin-top: 5px;">
                                    <a href="{{ 'reset-password'|link }}" class="small_btn-blk buy_now"><span class="small_blk-blk">{% trans 'Reset password' %}</span></a>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="grid_6 omega text last form">

                    {% if not request.register %}
                    <div class="box">
                        <h2>{% trans 'Do not have an account yet?' %}</h2>
                        <div class="block">
                            <a class="bb-button bb-button-red bb-button-big" href="#" onclick="$(this).parents('.box').hide(); $('#register-new-account').fadeIn(); return false;" style="margin: 30px 0 0 50px;">{% trans 'Register' %}</a>
                        </div>
                        {% if guest.extension_is_on({"mod":"oauth"}) %}
                            {% include "mod_oauth_buttons.phtml" with {"redirect_to":"cart"}%}
                        {% endif %}
                    </div>
                    {% endif %}

                    <div class="box" id="register-new-account" {% if not request.register %}style="display: none;"{% endif %} >
                            <h2>{% trans 'Enter your details below' %}</h2>
                            <div class="block">
                                {% set r = guest.client_required %}
                                <form action="guest/client/create" method="post" class="api-form" data-api-reload="1">
                              
                                        <legend>{% trans 'Create new profile' %}</legend>
                                        <p>
                                            <label>{% trans 'Email Address' %}: </label>
                                            <input type="email" name="email" value="{{ request.email }}" class="in" required id="reg-email">
                                        </p>
                                        <p>
                                            <label>{% trans 'First Name' %}: </label>
                                            <input type="text" name="first_name" value="{{ request.first_name }}" class="in" required>
                                        </p>

                                        {% if 'last_name' in r %}
                                        <p>
                                            <label>{% trans 'Last Name' %}: </label>
                                            <input type="text" name="last_name" value="{{ request.last_name }}" class="in" required>
                                        </p>
                                        {% endif %}

                                        {% if 'company' in r %}
                                        <p>
                                            <label>{% trans 'Company' %}: </label>
                                            <input type="text" name="company" value="{{ request.company }}" class="in" required>
                                        </p>
                                        {% endif %}

                                        {% if 'birthday' in r %}
                                        <p>
                                            <label>{% trans 'Birthday' %}: </label>
                                            <input type="text" name="birthday" value="" class="in" required>
                                        </p>
                                        {% endif %}

                                        {% if 'gender' in r %}
                                        <p>
                                            <label>{% trans 'You are' %}: </label>
                                            <select name="gender" class="in" required>
                                                <option value="male">Male</option>
                                                <option value="female">Female</option>
                                            </select>
                                        </p>
                                        {% endif %}

                                        {% if 'address_1' in r %}
                                        <p>
                                            <label>{% trans 'Address' %}: </label>
                                            <input type="text" name="address_1" class="in" value="{{ request.address_1 }}" required>
                                        </p>
                                        {% endif %}

                                        {% if 'address_2' in r %}
                                        <p>
                                            <label>{% trans 'Address 2' %}: </label>
                                            <input type="text" name="address_2" class="in" value="{{ request.address_2 }}" required>
                                        </p>
                                        {% endif %}

                                        {% if 'city' in r %}
                                        <p>
                                            <label>{% trans 'City' %}: </label>
                                            <input type="text" name="city" class="in" value="{{ request.city }}" required>
                                        </p>
                                        {% endif %}

                                        {% if 'country' in r %}
                                        <p>
                                            <label>{% trans 'Country' %}: </label>
                                            {{ mf.selectbox('country', guest.system_countries, request.country, 0, 'Select country') }}
                                        </p>
                                        {% endif %}

                                        {% if 'state' in r %}
                                        <p>
                                            <label>{% trans 'State' %}: </label>
                                            {# mf.selectbox('state', guest.system_states, request.state, 0, 'Select state') #}
                                            <input type="text" name="state" class="in" value="{{ request.state }}" />
                                        </p>
                                        {% endif %}

                                        {% if 'postcode' in r %}
                                        <p>
                                            <label>{% trans 'Zip/Postal Code' %}: </label>
                                            <input type="text" name="postcode" class="in" value="{{ request.postcode }}" required>
                                        </p>
                                        {% endif %}

                                        {% if 'phone' in r %}
                                        <p>
                                            <label>{% trans 'Phone' %}: </label>
                                            <br/>
                                            <input type="text" name="phone_cc" class="in" value="{{ request.phone_cc }}" required style="width: 30px; ">
                                            <input type="text" name="phone" class="in" value="{{ request.phone }}" requiredstyle="width: 230px; ">
                                        </p>
                                        {% endif %}

                                        <p>
                                            <label>{% trans 'Password' %}: </label>
                                            <input type="password" name="password" class="in" value="" required id="reg-password">
                                        </p>

                                        <p>
                                            <label>{% trans 'Password confirm' %}: </label>
                                            <input type="password" name="password_confirm" class="in" value="" required>
                                        </p>

                                        {{ mf.recaptcha }}
										<Br />
                                        <input class="bb-button bb-button-red" type="submit" value="" style="margin:0;">
                                        <input type="hidden" name="auto_login" value="1">
                               
                                </form>
                                </div>
                            </div>
                </div>
                <div class="clear"></div>
                </div>
            </div>
            
            {% endif %}
            <div class="clear"></div>
        </div>


{% else %}

<div class="h-block">
    <div class="h-block-header">
        <h2>{% trans 'You have not selected any product' %}</h2>
    </div>
    <div class="block">

        <div class="box">
            <a class="bb-button bb-button-red" href="{{ 'order'|link }}">{% trans 'Order new service' %}</a>
        </div>
        
    </div>
</div>

{% endif %}

</div>
{% endblock %}

{% block sidebar2 %}
    {% include 'partial_currency.phtml' %}
{% endblock %}

{% block js %}
<script type="text/javascript">
function onAfterCartCheckout(result)
{
    if(result.invoice_hash) {
        bb.redirect('{{"invoice"|link}}' + '/' + result.invoice_hash + '?auto_redirect=1');
    } else {
        bb.redirect('{{"service/manage"|link}}' + '/' + result.order_id );
    }
}
</script>
{% endblock %}