{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Invoices' %}{% endblock %}

{% block page_title_up %}
{% trans 'Invoices' %}
<p>{% trans 'List of invoices' %}</p>
{% endblock %}

{% block content %}

{% set unpaid_invoices = client.invoice_get_list({"status":"unpaid", "per_page":100}).list %}
<h2>{% trans 'Invoice management' %}</h2>

        <div class="block conversation">
        <div class="widget simpleTabs tabsRight first">
        <ul class="tabs">
            {% if unpaid_invoices|length %}
            <li><a href="#tab-unpaid">{% trans 'Unpaid' %}</a></li>
            {% endif %}
            <li><a href="#tab-paid">{% trans 'Paid' %}</a></li>
        </ul>
        <Br /><br /><Br />
        
        
        <div class="tabs_container">
            
            {% if unpaid_invoices|length %}
            <div class="tab_content" id="tab-unpaid">
            <div style="clear:both;"></div>
            <div class="domains"> 
			 <div class="gray">
                    	<span class="title">{% trans 'Title' %}</span>
                        <span class="title" style="width: 120px !important;">{% trans 'Issue Date' %}</span>
                        <span class="title">{% trans 'Due Date' %}</span>
                        <span class="title" style="width: 60px !important;">{% trans 'Total' %}</span>
                        <span class="title last" style="width: 30px !important;">&nbsp;</span>
                        <div class="clear"></div>
                    </div>

                    {% for i, invoice in unpaid_invoices %}
                    <div class="{{ cycle(['light', 'dark'], i) }}">
                    	<span class="detail">{{ "Proforma invoice #%05s"|format(invoice.id) }}</span>
                        <span class="detail" style="width: 120px !important;">{{ invoice.created_at|bb_date }}</span>
                        <span class="detail">{{ invoice.due_at|bb_date }}</span>
                        <span class="detail" style="width: 60px !important;">{{ invoice.total | money(invoice.currency) }}</span>
                        <span class="detail" style="width: 30px !important;"><a class="bb-button bb-button-red" href="{{ 'invoice'|link }}/{{ invoice.hash }}">{% trans 'Pay' %}</a></span>
                        <div class="clear"></div>
                    </div>
                    {% else %}
                    <div class="{{ cycle(['light', 'dark'], i) }}">
                    <span class="detail" style="width: 100% !important;">{% trans 'The list is empty' %}</span>
                	</div>
                    {% endfor %}

        </div>
        </div>
        {% endif %}
        
        <div class="tab_content" id="tab-paid">
        
        
        <div class="domains"> 
			 <div class="gray">
                    	<span class="title">{% trans 'Title' %}</span>
                        <span class="title" style="width: 120px !important;">{% trans 'Issue Date' %}</span>
                        <span class="title">{% trans 'Paid at' %}</span>
                        <span class="title" style="width: 60px !important;">{% trans 'Total' %}</span>
                        <span class="title last" style="width: 30px !important;">&nbsp;</span>
                        <div class="clear"></div>
                    </div>

       
                    {% set paid_invoices = client.invoice_get_list({"per_page":10, "page":request.page, "status":"paid"}) %}
                    {% for i, invoice in paid_invoices.list %}
					<div class="{{ cycle(['light', 'dark'], i) }}">
                    	<span class="detail">{{ "Proforma invoice #%05s"|format(invoice.id) }}</span>
                        <span class="detail" style="width: 120px !important;">{{ invoice.created_at|bb_date }}</span>
                        <span class="detail">{{ invoice.paid_at|bb_date }}</span>
                        <span class="detail" style="width: 60px !important;">{{ invoice.total | money(invoice.currency) }}</span>
                        <span class="detail" style="width: 30px !important;"><a class="bb-button" href="{{ 'invoice'|link }}/{{ invoice.hash }}">Show</a></span>
                        <div class="clear"></div>
                    </div>
                    {% else %}
                    <div class="{{ cycle(['light', 'dark'], i) }}">
                    <span class="detail" style="width: 100% !important;">{% trans 'The list is empty' %}</span>
                	</div>
                    <div style="clear:both;"></div>
                    {% endfor %}
           
            {% include "partial_pagination.phtml" with {'list': paid_invoices} %}
            
        </div>
    </div>
</div>
</div>
</div>

{% endblock %}
