{% extends request.ajax ? "layout_blank.phtml" : "layout_default_tab.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Support tickets' %}{% endblock %}

{% block page_title_up %}
{% trans 'Support tickets' %}
{% endblock %}

{% block content %}
 <div class="domains"> 
 <div class="gray">
                    	<span class="title">{% trans 'Id' %}</span>
                        <span class="title">{% trans 'Subject' %}</span>
                        <span class="title">{% trans 'Help desk' %}</span>
                        <span class="title" style="width: 80px !important;">{% trans 'Status' %}</span>
                        <span class="title">{% trans 'Submitted' %}</span>
                        <span class="title last" style="width: 40px !important;"></span>
                        <div class="clear"></div>
                    </div>

                    {% set tickets = client.support_ticket_get_list({"per_page":10, "page":request.page}) %}
                    {% for i, ticket in tickets.list %}
                    <div class="{{ cycle(['light', 'dark'], i) }}">
                    	<span class="detail">#{{ticket.id}}</span>
                        <span class="detail"><a href="{{ 'support/ticket'|link }}/{{ticket.id}}">{{ticket.subject|truncate(40)}}</a></span>
                        <span class="detail">{{ticket.helpdesk.name}}</span>
                        <span class="detail" style="width: 80px !important;">{{mf.status_name(ticket.status)}}</span>
                        <span class="detail last">{{ticket.created_at|timeago}} {% trans 'ago' %}</span>
                        <span class="detail last"><a class="bb-button" href="{{ 'support/ticket'|link }}/{{ticket.id}}">Show</a></span>
                        <div class="clear"></div>
                    </div>
                    {% else %}
					<div class="light">
                    <span style="width:100%;">{% trans 'The list is empty' %}</span>
                    {% endfor %}

</div>
<a href="#" class="small_btn-org table_btn" id="new-ticket-button"><span class="small_blk-org">{% trans 'Submit new ticket' %}</span></a>

{% include "partial_pagination.phtml" with {'list': tickets} %}
</div>

</div>

<div style="clear:both;"></div>

<div class="white_bg" id="new-ticket" {% if not request.ticket %}style="display: none;"{% endif %}>

<div class="container">

        <h2>{% trans 'Submit new ticket' %}</h2>

    <div class="form" style="float:left;">
        <form action="" method="post" id="ticket-submit">
                <legend>{% trans 'Submit new support ticket' %}</legend>
                
                <div class="field">
             	<label>{% trans 'Help desk' %}:</label>
                {{ mf.selectbox('support_helpdesk_id', client.support_helpdesk_get_pairs, request.support_helpdesk_id, 1) }}
                </div>
                <div style="clear:both;"></div>
                <div class="field">
             	<label>{% trans 'Subject' %}:</label>
                <input name="subject" id="name" type="text" id="subject" value="{{ request.subject|e }}" required="required">
                </div>
                
                <div class="field">
                    	<label>{% trans 'Message' %}:</label>
                        <textarea name="content" id="message" cols="" rows="" required="required">{{ request.content|e }}</textarea>
                </div>

				
				<br />
                
                <input class="bb-button bb-button-submit comment_submit" type="submit" value="">
        </form>
</div>
<div style="clear:both;"></div>
</div>

</div>

<div class="container">


{% if guest.extension_is_on({"mod":'kb'}) %}
<br /><br />
<div class="text">
        <h2>{%trans 'Knowledge base'%}</h2>
    <ul>
    {% for i, category in guest.kb_category_get_list.list %}
    <li><a href="{{ '/kb'|link }}#category-{{category.id}}">{{category.title}}</a></li>
    {% endfor %}
    </ul>
</div>
{% endif %}
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
$(function() {

    $('#new-ticket-button').bind('click',function(event){
        $('#new-ticket').slideToggle();
        return false;
    });

    $('#ticket-submit').bind('submit',function(event){
        bb.post(
            'client/support/ticket_create',
            $(this).serialize(),
            function(result) {
                bb.redirect('{{ 'support/ticket'|link }}' + '/' + result);
            }
        );
        return false;
    });

});
</script>
{% endblock %}