{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{% trans 'Emails' %}{% endblock %}

{% block page_title_up %}
{% trans 'Emails we have sent you'%}
{% endblock %}

{% block content %}

<div class="domains"> 
<div class="gray">
                    	<span class="title">{% trans 'Email subject' %}</span>
                        <span class="title">{% trans 'To' %}</span>
                        <span class="title" style="width:100px !important;">{% trans 'Date sent' %}</span>
                        <span class="title" style="width:60px !important;">&nbsp;</span>
                        <div class="clear"></div>
                    </div>

                {% set emails = client.email_get_list({"per_page":10, "page":request.page}) %}
                {% for i, email in emails.list %}
                
                <div class="{{ cycle(['light', 'dark'], i) }}">
                    	<span class="detail"><a href="{{ 'email'|link }}/{{email.id}}">{{email.subject}}</a></span>
                        <span class="detail">{{ email.recipients }}</span>
                        <span class="detail">{{email.created_at|bb_date}}</span>
                        <span class="detail"><a class="bb-button" href="{{ 'email'|link }}/{{email.id}}">Show</a></span>
                        <div class="clear"></div>
                    </div>

                {% else %}
                    <div class="light">
                    <span style="width:100%;">{% trans 'The list is empty' %}</span>
                    </div>
                {% endfor %}

</div>

{% include "partial_pagination.phtml" with {'list': emails} %}

{% endblock %}
