
<center>
<div id="psteps_circle_steps_simple" class="pf-form" style="width: 100%; margin-left: 15%; margin-bottom:10px;">
		<div class="row-fluid">
			<div class="psteps_circle_titles" style="width: 100%;">
				<div class="step-title circle-step {% if selected == 1 %} btn step-visited pstep1 btn-success{% endif %} {% if selected > 1 %} btn step-visited pstep1 btn-success disabled last-active{% endif %}"><span class="step-order">1</span><span class="step-name hide">{% trans 'Select product' %}</span></div><div class="step-line"></div>
				<div class="step-title circle-step {% if selected == 2 %} btn step-visited pstep1 btn-success{% endif %} {% if selected > 2 %} btn step-visited pstep1 btn-success disabled last-active{% endif %}"><span class="step-order">2</span><span class="step-name hide">{% trans 'Configure' %}</span></div><div class="step-line"></div>
				<div class="step-title circle-step {% if selected == 3 %} btn step-visited pstep1 btn-success{% endif %} {% if selected > 3 %} btn step-visited pstep1 btn-success disabled last-active{% endif %}"><span class="step-order">3</span><span class="step-name hide">{% trans 'Confirm' %}</span></div><div class="step-line"></div>
				<div class="step-title circle-step {% if selected == 4 %} btn step-visited pstep1 btn-success{% endif %} {% if selected > 4 %} btn step-visited pstep1 btn-success disabled last-active{% endif %}"><span class="step-order">4</span><span class="step-name hide">{% trans 'Checkout' %}</span></div>

			</div>
		</div>				
</div>
</center>